
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dependencies
```{r}
library(tidyverse)
```


## Reading in the Datasets
```{r}
game_rushing <- read_csv('SeniorYearND/MachineLearning/FinalProject/Datasets/game_rushing_df.csv')

game_passing <- read_csv('SeniorYearND/MachineLearning/FinalProject/Datasets/game_passing_df.csv')

game_2009 <- read_csv('SeniorYearND/MachineLearning/FinalProject/Datasets/games_2009.csv')

game_2010 <- read_csv('SeniorYearND/MachineLearning/FinalProject/Datasets/games_2010.csv')

game_2011 <- read_csv('SeniorYearND/MachineLearning/FinalProject/Datasets/games_2011.csv')

game_2012 <- read_csv('SeniorYearND/MachineLearning/FinalProject/Datasets/games_2012.csv')

game_2013 <- read_csv('SeniorYearND/MachineLearning/FinalProject/Datasets/games_2013.csv')

game_2014 <- read_csv('SeniorYearND/MachineLearning/FinalProject/Datasets/games_2014.csv')

game_2015 <- read_csv('SeniorYearND/MachineLearning/FinalProject/Datasets/games_2015.csv')

game_2016 <- read_csv('SeniorYearND/MachineLearning/FinalProject/Datasets/games_2016.csv')

game_2017 <- read_csv('SeniorYearND/MachineLearning/FinalProject/Datasets/games_2017.csv')
```
## Combining the Datasets
```{r}
game_scores <- rbind(game_2009, game_2010, game_2011, game_2012, game_2013, game_2014, game_2015, game_2016, game_2017)

game_rushing_scores <- left_join(game_rushing, game_scores, by = 'GameID', copy = FALSE)


for(i in 1:nrow(game_rushing_scores)) {
  if (game_rushing_scores[i, 'Team'] == game_rushing_scores[i, 'home']) {
    game_rushing_scores[i, 'home_flag'] <- '1'
  }
  else {
    game_rushing_scores[i, 'home_flag'] <- '0'
  }
}
```

